# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR

on:
  workflow_call:

jobs:
  pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            autorelease: pending

  # milestone:
  #   name: Add to milestone
  #   if: github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: write
  #   steps:
  #     - name: Add Current Milestone
  #       uses: benelan/milestone-action@v3
  #       with:
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}

  # label:
  #   name: Add type label
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: write
  #     issues: write
  #   steps:
  #     - name: Add Conventional Type Label
  #       uses: actions/github-script@v7
  #       with:
  #         script: |
  #           const script = require('${{ github.workspace }}/scripts/label.js')
  #           await script({github, context, core})
